theme: jekyll-theme-cayman
title: AI, Proof and Verification (AIPV)
subtitle: May 18-19, 2026. Colocated with FM2026 in Tokyo.
email: nagashima+cs.cas.cz (replace + with @)
description: >- # this means to ignore newlines until "baseurl:"
  Colocated with FM2026 in Tokyo
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Add links to the subpages
navigation:
  - name: Home
    link: /
#  - name: Research
#    link: /research
#  - name: Publication
#    link: /publication

# Navigation links
header_pages:
  - index.markdown           # Root level page
#  - research/index.markdown  # Only show this research page
#  - publication.markdown

twitter_username: YutakangE
github_username:  yutakang
mastodon_username: yutakang_en
mastodon_instance: mastodon.social
youtube_channel: unitedreasoning
bluesky_username: yutaka-en
